id: I0F004A25
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:23:45+00:00'
last_modified: '2022-06-07T15:23:40.441613+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16575
  title: ཡིག་གཟུགས་ཀྱི་ཀ་དཔེ་སློབ་མའི་སྙིང་ནོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A009:
      image_group_id: I2PD17869
      title: ''
      total_pages: 56
      order: 1
      base_file: A009.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
