id: P001854
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:26:12.760394
source_metadata:
  id: bdr:W1KG16575
  title: ཡིག་གཟུགས་ཀྱི་ཀ་དཔེ་སློབ་མའི་སྙིང་ནོར།
  author: ''
  volumes:
    99d209b934864ee285762f16a05a77b4:
      image_group_id: I2PD17869
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
